title: Hello there.
author: Yusafio
email: yusuf70704@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is not a page.

# social links
twitter_username: evil_murfy # DO NOT include the @ character, or else the build will fail!
github_username:  Yusafio # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
